server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

integrations:
  cart-service:
    url: http://cart-service:8190/market-cart/
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000